service: serverless-goof

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: google
  project: snyk-presentations
  region: us-central1
  runtime: nodejs6
  credentials: ~/.gcloud/keyfile.json
  environment:
    MY_SECRET_ENV_VAR: "Tada!"

plugins:
  - serverless-google-cloudfunctions

functions:
  todosApi:
    handler: todos
    events:
      - http: todos

  # internalBackup:
  #   handler: internalBackup
  #   events:
  #     - event:
  #         path: admin/backup

  # internalRestore:
  #   handler: internalRestore
  #   events:
  #     - http:
  #         path: admin/restore

  adminApi:
    handler: admin
    events:
      - http: admin
